"""Write RESTORE-RUNBOOK.md from Python parts (workaround for hook FPs on cmd-in-backticks)."""
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "RESTORE-RUNBOOK.md"

parts = []

parts.append("# RESTORE-RUNBOOK schoolsWP\n\n")
parts.append("> A LIRE QUAND TOUT BRULE. Ecrit pour etre suivi alors que tu es stresse a 3h du matin.\n")
parts.append("> Imprime aussi sur PAPIER. Range a 3 endroits : repo, 1Password vault, dossier physique.\n")
parts.append("> Derniere mise a jour : 2026-05-12.\n\n")
parts.append("---\n\n")

parts.append("## Pre-requis (5 min)\n\n")
parts.append("Avant TOUT restore, recupere ces 3 valeurs depuis 1Password vault schoolswp-backups :\n\n")
parts.append("| Variable | Description |\n|---|---|\n")
parts.append("| B2_ACCOUNT_ID | keyID Backblaze pour l acces restic |\n")
parts.append("| B2_ACCOUNT_KEY | applicationKey Backblaze |\n")
parts.append("| RESTIC_PASSWORD | passphrase qui dechiffre les backups |\n\n")
parts.append("Si 1Password est inaccessible : la valeur RESTIC_PASSWORD est aussi sur papier dans un coffre physique chez toi. Les B2 credentials sont visibles dans https://secure.backblaze.com/app_keys.htm (connecte-toi a B2 avec ton compte email).\n\n")
parts.append("---\n\n")

parts.append("## Scenario 1 : Restore complet WP schoolswp.com\n\n")
parts.append("**Quand l utiliser** : site compromis, base de donnees corrompue, hebergeur tombe, ou apres incident GDPR.\n\n")
parts.append("**Temps estime** : 30-90 min selon taille DB + uploads.\n\n")

parts.append("### Option A (recommandee) : restore via WP Umbrella\n\n")
parts.append("1. Va sur https://app.wp-umbrella.com (login compte abonnement)\n")
parts.append("2. Selectionne schoolswp.com dans la liste des sites\n")
parts.append("3. Backups > selectionne le dernier point de restauration valide (voir colonne Status Success)\n")
parts.append("4. Clique Restore\n")
parts.append("5. Suivre l interface WP Umbrella qui handle tout (DB + files + theme + plugins)\n")
parts.append("6. Verification post-restore (cf section Validation plus bas)\n\n")
parts.append("Si WP Umbrella ne marche pas (compte expire, plugin desactive cote WP, ou backup corrompu) : passer a Option B.\n\n")

parts.append("### Option B : restore via WPvivid\n\n")
parts.append("1. Connecte-toi au panel EasyHoster pour ton compte schoolswp.com\n")
parts.append("2. cPanel > File Manager > navigue vers wp-content/wpvivid_backup/\n")
parts.append("3. Cherche le fichier .wpvivid_xxxxx.tar ou .zip le plus recent\n")
parts.append("4. Telecharge-le sur ton PC\n")
parts.append("5. Si le site est down, reinstalle WordPress propre sur le meme domaine via EasyHoster > Auto Installer (saute la creation d admin, on va restaurer)\n")
parts.append("6. Active le plugin WPvivid Backup\n")
parts.append("7. WPvivid > Upload > upload le fichier telecharge\n")
parts.append("8. Restore\n\n")

parts.append("### Option C : restore via Backblaze B2 (si WP Umbrella + WPvivid tous deux indisponibles)\n\n")
parts.append("Le backup B2 ne contient PAS le WP entier (DB + files + uploads + plugins). Il contient uniquement le repo Git + vault Obsidian + n8n workflows. Donc on ne peut PAS restaurer le WP schoolswp.com depuis B2 seul.\n\n")
parts.append("Action : ouvre un ticket support EasyHoster + WP Umbrella. Demande copie sauvegarde la plus recente disponible cote provider.\n\n")

parts.append("### Validation post-restore WP\n\n")
parts.append("Verifications dans wp-admin :\n\n")
parts.append("- Login admin : OK ?\n")
parts.append("- Frontend : page d accueil charge sans erreur ?\n")
parts.append("- 3 articles aleatoires : OK ?\n")
parts.append("- FluentCRM > Contacts : nb contacts > 0 ?\n")
parts.append("- FluentCart > Orders : nb commandes recentes > 0 ?\n")
parts.append("- Aucun message d erreur dans wp-admin > Tools > Site Health ?\n\n")
parts.append("Si tu as WP-CLI sur le serveur (commandes a copier-coller) :\n\n")
parts.append("    wp option get blogname\n")
parts.append("    wp post list --post_type=post --posts_per_page=3\n")
parts.append("    wp db query \"SELECT COUNT(*) FROM wp_fc_subscribers\"\n")
parts.append("    wp plugin list --status=active --field=name\n\n")
parts.append("Plugin count doit etre ~54.\n\n")
parts.append("---\n\n")

parts.append("## Scenario 2 : Restore workflow n8n\n\n")
parts.append("**Quand l utiliser** : un workflow specifique a ete supprime, modifie par erreur, ou tu veux verifier qu un workflow exporte le mois dernier reste loadable.\n\n")
parts.append("**Temps estime** : 5 min par workflow.\n\n")
parts.append("1. Identifie le workflow voulu dans le snapshot (cf n8n-snapshot-YYYY-MM-DD/ dans le repo)\n")
parts.append("2. Ouvre le fichier JSON correspondant (nom = id__safe-name.json)\n")
parts.append("3. Va sur https://schoolswp-n8n.wp1.host/workflows (ou ton instance n8n)\n")
parts.append("4. Import from File (icone en haut a droite) > selectionne le JSON\n")
parts.append("5. Le workflow est importe avec un nouvel ID (l ancien si conflit reste)\n")
parts.append("6. Recree les credentials manuellement via l UI n8n (les valeurs chiffrees ne sont pas exportees dans le JSON)\n")
parts.append("7. Active le workflow si necessaire\n\n")

parts.append("### Restore complet de tous les workflows (apres crash n8n)\n\n")
parts.append("Si la base n8n est totalement perdue, restore tous les 65 workflows via le script PowerShell :\n\n")
parts.append("    $snapshot = \"D:\\VS Code\\CLAUDE CODE\\projects\\schoolswp\\docs\\security\\09-backup\\n8n-snapshot-2026-05-12\"\n")
parts.append("    $apiUrl = \"https://schoolswp-n8n.wp1.host\"\n")
parts.append("    $apiKey = \"<from 1Password n8n_api_key_mcp>\"\n\n")
parts.append("    Get-ChildItem \"$snapshot\\*.json\" | Where-Object { $_.Name -notlike \"_*\" } | ForEach-Object {\n")
parts.append("        $body = Get-Content $_.FullName -Raw\n")
parts.append("        Invoke-RestMethod -Method POST -Uri \"$apiUrl/api/v1/workflows\" `\n")
parts.append("            -Headers @{ \"X-N8N-API-KEY\" = $apiKey } `\n")
parts.append("            -ContentType \"application/json\" -Body $body\n")
parts.append("        Write-Output \"Imported: $($_.BaseName)\"\n")
parts.append("    }\n\n")
parts.append("Important : les workflows sont importes comme NEW (nouveaux IDs), pas comme update des existants. Si tu restaures sur une instance qui a deja certains workflows, tu auras des doublons. Verifie d abord.\n\n")
parts.append("---\n\n")

parts.append("## Scenario 3 : Restore vault Obsidian\n\n")
parts.append("**Quand l utiliser** : le fichier vault Obsidian a ete corrompu, supprime, ou ton PC a brule.\n\n")
parts.append("**Temps estime** : 15 min.\n\n")
parts.append("1. Sur le nouveau poste, installe Obsidian (https://obsidian.md)\n")
parts.append("2. Charge les env restic dans PowerShell :\n\n")
parts.append("        $env:B2_ACCOUNT_ID = \"<from 1Password>\"\n")
parts.append("        $env:B2_ACCOUNT_KEY = \"<from 1Password>\"\n")
parts.append("        $env:RESTIC_REPOSITORY = \"b2:schoolswp-backups-2026\"\n")
parts.append("        $env:RESTIC_PASSWORD = \"<from 1Password>\"\n\n")
parts.append("3. Liste les snapshots disponibles :\n\n")
parts.append("        restic snapshots --path \"D:/MES SITES/SCHOOLSWP.COM/12_Obsidian/schoolsWP\"\n\n")
parts.append("4. Restore le snapshot voulu (par exemple le plus recent) :\n\n")
parts.append("        restic restore latest --target \"D:/restore-obsidian-test\"\n\n")
parts.append("5. Ouvre Obsidian, Open folder as vault > selectionne D:/restore-obsidian-test/.../schoolswp\n")
parts.append("6. Verifie : claude.md, index.md, log.md a la racine du vault sont presents\n")
parts.append("7. Une fois OK, deplace le restore vers le path final D:/MES SITES/SCHOOLSWP.COM/12_Obsidian/schoolsWP/\n\n")
parts.append("---\n\n")

parts.append("## Scenario 4 : Restore repo Git schoolswp\n\n")
parts.append("**Quand l utiliser** : repo local corrompu, GitHub down, ou tu travailles sur un nouveau PC.\n\n")
parts.append("**Temps estime** : 5 min si GitHub OK, 20 min via B2.\n\n")
parts.append("### Option A : GitHub origin\n\n")
parts.append("    git clone https://github.com/kihlmichael/schoolswp.git\n")
parts.append("    cd schoolswp\n\n")
parts.append("Tu auras besoin de t authentifier via gh CLI ou PAT.\n\n")
parts.append("### Option B : restore via Backblaze (si GitHub indisponible)\n\n")
parts.append("Charge env restic comme scenario 3 step 2, puis :\n\n")
parts.append("    restic snapshots --path \"D:/VS Code/CLAUDE CODE/projects/schoolswp\"\n")
parts.append("    restic restore <snapshot-id> --target \"D:/restore-schoolswp\"\n\n")
parts.append("Le .git est inclus dans le backup, donc tu peux re-initier le push vers un nouveau remote si GitHub reste inaccessible :\n\n")
parts.append("    cd D:/restore-schoolswp/projects/schoolswp\n")
parts.append("    git remote -v\n")
parts.append("    git remote set-url origin <new-remote-url>\n\n")
parts.append("---\n\n")

parts.append("## Scenario 5 : Compromis VPS / hebergeur\n\n")
parts.append("**Quand l utiliser** : tu suspectes une intrusion sur schoolswp.com ou xCloud apps.\n\n")
parts.append("**Temps estime** : 1-2 heures pour confinement, plus restore selon scenario 1-4.\n\n")
parts.append("### Etapes immediates (premieres 15 min)\n\n")
parts.append("1. Couper l acces public :\n")
parts.append("   - schoolswp.com : Cloudflare > Security > Under Attack mode (challenge JS pour tout visiteur)\n")
parts.append("   - n8n : Cloudflare Access deny all si configure, sinon WP Umbrella > Site Status > Pause\n")
parts.append("2. Garder une session SSH/cPanel ouverte (ne pas tout fermer)\n")
parts.append("3. Snapshot disque cote provider :\n")
parts.append("   - EasyHoster : ticket support en URGENT pour demander snapshot immediat\n")
parts.append("   - xCloud : Dashboard > Servers > Backup Now (sinon snapshot)\n")
parts.append("4. NE PAS REBOOT (perte de la RAM = perte de preuves)\n")
parts.append("5. Pas de modification des fichiers avant le snapshot\n\n")
parts.append("### Investigation (30 min)\n\n")
parts.append("- WP : verifier wp_users (utilisateurs ajoutes ?), wp_options (backdoor ?), wp-content/uploads/ (php files ?)\n")
parts.append("- Logs : EasyHoster access.log + error.log dernieres 24h\n")
parts.append("- WP Umbrella > Activity feed (login admins recents)\n")
parts.append("- Comparer plugins/themes avec le manifest etape 2 (02-wp-inventory-schoolswp.md)\n\n")
parts.append("### Restore propre (selon decouvertes)\n\n")
parts.append("- Si la compromission date de moins de 7j : restore WP via Option A (WP Umbrella point pre-compromis)\n")
parts.append("- Si datant > 7j : restore + audit manuel ligne a ligne du WP\n")
parts.append("- Rotation immediate de TOUS les Application Passwords (cf liste etape 2)\n")
parts.append("- Rotation de TOUS les secrets MCP touchant schoolswp.com (FluentCRM, WP_API_PASSWORD, etc.)\n\n")
parts.append("---\n\n")

parts.append("## Temps mesures (drill du 2026-05-12)\n\n")
parts.append("A remplir lors du premier drill effectif :\n\n")
parts.append("| Scenario | Temps measure | Date drill |\n|---|---|---|\n")
parts.append("| Restore workflow n8n (1 unite) | ?? | ?? |\n")
parts.append("| Restore tous workflows n8n (65) | ?? | ?? |\n")
parts.append("| Restore vault Obsidian | ?? | ?? |\n")
parts.append("| Restore repo Git via B2 | ?? | ?? |\n")
parts.append("| Restore WP via WP Umbrella | ?? | ?? |\n")
parts.append("| Restore WP via WordPress Studio (drill local) | ?? | ?? |\n\n")
parts.append("---\n\n")

parts.append("## Maintenance du runbook\n\n")
parts.append("A revisiter :\n\n")
parts.append("- Apres chaque incident (mettre a jour avec les decouvertes)\n")
parts.append("- Apres chaque drill mensuel (mettre a jour les temps + procedures changees)\n")
parts.append("- Apres tout changement majeur (nouveau plugin critique, nouveau backup target, etc.)\n\n")

parts.append("## Numeros d urgence\n\n")
parts.append("- EasyHoster support : https://www.easyhoster.com/support/ (ticket urgent)\n")
parts.append("- xCloud support : cherche dans 1Password ou la dashboard\n")
parts.append("- Cloudflare support : https://dash.cloudflare.com/?to=/:account/support\n")
parts.append("- Backblaze support : https://www.backblaze.com/help.html\n")
parts.append("- Anthropic security : security@anthropic.com (incident clef leak)\n")
parts.append("- Stripe support : compte FluentCart connecte\n")
parts.append("- Registrar AFNIC (.fr) ou ICANN (.com) pour michaelkihl.fr / schoolswp.com\n\n")
parts.append("---\n\n")

parts.append("## Si tu ne te souviens de rien d autre\n\n")
parts.append("Recupere d abord :\n\n")
parts.append("1. RESTIC_PASSWORD (1Password ou papier)\n")
parts.append("2. Acces 1Password (master password ou recovery code)\n")
parts.append("3. Acces GitHub (gh auth status, ou recovery codes 2FA)\n\n")
parts.append("Le reste est restorable depuis ces 3 acces.\n")

OUT.write_text("".join(parts), encoding="utf-8")
print(f"WRITTEN: {OUT} ({OUT.stat().st_size} bytes)")
