"""Write v2 tab to source spreadsheet with merged + enriched data."""

from pathlib import Path

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

SHEET_ID = "1YLtlrrOgZAdyamYdEu_uOLz5lzvSJKfS4ykDCSfjKm8"
TOKEN = Path(__file__).parent / "token-cci-v2.json"
SCOPES = ["https://www.googleapis.com/auth/drive", "https://www.googleapis.com/auth/spreadsheets"]
creds = Credentials.from_authorized_user_file(str(TOKEN), SCOPES)
svc = build("sheets", "v4", credentials=creds)

HEADERS = [
    "ID",
    "Intitule",
    "Pertinence schoolsWP (/10)",
    "Priorite",
    "Statut",
    "Thematique",
    "Format",
    "Ville",
    "Source",
    "Duree",
    "Tarif TTC",
    "CPF/Certif",
    "Sessions 2026",
    "Pourquoi pour toi / Commentaire strategique",
    "Action recommandee",
    "Rapprochement base Metz v1",
    "Notes de verification",
    "URL",
]

# E = Existante (Formations triees v1), N = Nouvelle, Nouvelle = scrape 2026-04
ROWS = [
    # --- 11 existantes, conservees + harmonisees ---
    [
        "1",
        "Formation de formateur - CCE",
        "10/10 ESSENTIELLE",
        "Priorite 1",
        "Deja presente (v1 #1)",
        "RH / Formation",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "5 jours (35h)",
        "1690 EUR (+500 CCE)",
        "Oui (RS5365)",
        "22-26 juin / 7-11 sept / 2-6 nov",
        "Valide ta competence formateur (TutorLMS, FluentCRM, OttoKit). 100% reussite 2024. Pilier autorite schoolsWP.",
        "A inscrire session sept ou nov 2026",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/ressources-humaines/formation-de-formateur-cce",
    ],
    [
        "2",
        "IA - Dirigeants et CODIR",
        "9/10 TRES HAUTE",
        "Priorite 1",
        "Deja presente (v1 #2)",
        "Intelligence artificielle",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "1 jour (7h)",
        "420 EUR",
        "Non",
        "8 avr / 3 juin / 9 sept / 28 oct / 9 dec",
        "Pilotage strategique schoolsWP avec IA. Decision, veille, SWOT. Directement applicable.",
        "A etudier en priorite - session 3 juin",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/intelligence-artificielle/optimiser-son-travail-au-quotidien-avec-lintelligence-3",
    ],
    [
        "3",
        "IA - Commerciaux",
        "9/10 TRES HAUTE",
        "Priorite 1",
        "Deja presente (v1 #3)",
        "Intelligence artificielle",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "1 jour (7h)",
        "420 EUR",
        "Non",
        "9 avr / 4 juin / 8 sept / 29 oct / 8 dec",
        "Prospection IA, pitch, relance automatisee, veille. Essentiel dev activite + affiliations.",
        "A etudier en priorite - session 4 juin",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/intelligence-artificielle/optimiser-son-travail-au-quotidien-avec-lintelligence",
    ],
    [
        "4",
        "Creation entreprise (5JPE)",
        "8/10 HAUTE",
        "Priorite 1",
        "Deja presente (v1 #4)",
        "Creation/Reprise",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "5 jours (35h)",
        "750 EUR",
        "Oui (RS6923)",
        "1-9 juin 2026",
        "Formaliser business model schoolsWP, strategie commerciale, choix juridique. 91% satisfaction.",
        "A contacter pour reserver juin 2026",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/formations-creation-reprise-dentreprises/creation-entreprise-identifier-les-points-cles",
    ],
    [
        "5",
        "Excel TCD + IA",
        "8/10 HAUTE",
        "Priorite 2",
        "Deja presente (v1 #5)",
        "Bureautique",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "1 jour (7h)",
        "240 EUR",
        "Non",
        "Sur demande",
        "Analyse GA4, reporting SEO, suivi formations, KPI schoolsWP. Meilleur prix catalogue. Inclut Copilot/ChatGPT.",
        "A planifier - sur demande",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/bureautique/excel-tableaux-croises-dynamiques",
    ],
    [
        "6",
        "Batir un projet entrepreneurial durable",
        "8/10 HAUTE",
        "Priorite 2",
        "Deja presente (v1 #6)",
        "Creation/Reprise",
        "Presentiel ou distance",
        "Metz",
        "moselle.cci.fr",
        "7h sur 2-4 mois",
        "875 EUR",
        "Oui (RS5579)",
        "Entrees permanentes",
        "Business plan complet, format individuel flexible. Ideal pour structurer schoolsWP en entreprise perenne.",
        "A etudier - entrees permanentes",
        "Conservee v1",
        "OK",
        "https://www.moselle.cci.fr/produit/batir-un-projet-entrepreneurial-durable",
    ],
    [
        "7",
        "IA - Managers / Resp. operationnels",
        "6/10 MOYENNE",
        "Priorite 3",
        "Deja presente (v1 #7)",
        "Intelligence artificielle",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "1 jour (7h)",
        "420 EUR",
        "Non",
        "Sessions identiques IA",
        "Pilotage equipes/process avec IA. Utile si delegation ou sous-traitance.",
        "A surveiller - pas prioritaire",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/intelligence-artificielle/optimiser-son-travail-au-quotidien-avec-lintelligence-1",
    ],
    [
        "8",
        "IA - Assistants admin/ADV",
        "5/10 MOYENNE",
        "Priorite 3",
        "Deja presente (v1 #8)",
        "Intelligence artificielle",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "1 jour (7h)",
        "420 EUR",
        "Non",
        "Sessions identiques IA",
        "Automatiser taches admin avec IA. Utile gain de temps gestion quotidienne.",
        "A surveiller",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/intelligence-artificielle/optimiser-son-travail-au-quotidien-avec-lintelligence-2",
    ],
    [
        "9",
        "Premiers secours sante mentale",
        "5/10 MOYENNE",
        "Priorite 3",
        "Deja presente (v1 #9)",
        "QVT / Bien-etre",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "2 jours (14h)",
        "760 EUR",
        "Non",
        "Sur demande",
        "Prevention sante mentale. Pertinent bien-etre solopreneur + si tu formes.",
        "A confirmer - utilite personnelle",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/qualite-de-vie-bien-etre-au-travail/premiers-secours-en-sante-mentale",
    ],
    [
        "10",
        "Droit local Alsace/Moselle",
        "3/10 BASSE",
        "Priorite 3",
        "Deja presente (v1 #10)",
        "RH / Droit",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "1 jour (7h)",
        "590 EUR",
        "Non",
        "Sur demande",
        "Specifique region. Utile uniquement si embauche en Moselle.",
        "A ecarter sauf embauche",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/ressources-humaines/le-droit-local-alsace-moselle",
    ],
    [
        "11",
        "Manager la diversite",
        "2/10 BASSE",
        "Priorite 3",
        "Deja presente (v1 #11)",
        "Management",
        "Presentiel",
        "Metz",
        "campus-moselle",
        "2 jours (14h)",
        "760 EUR",
        "Non",
        "Sur demande",
        "Peu pertinent solopreneur sauf management d'equipe.",
        "A ecarter",
        "Conservee v1",
        "OK",
        "https://www.campus-moselle.cci.fr/formations/management/manager-la-diversite",
    ],
    # --- NOUVELLES formations Metz decouvertes via scrape campus-moselle ---
    [
        "12",
        "Maitriser les fondamentaux de la vente (+ IA)",
        "9/10 TRES HAUTE",
        "Priorite 1",
        "Nouvelle",
        "Commercial / Vente",
        "Presentiel ou visio",
        "Metz",
        "campus-moselle",
        "A verifier (non affiche)",
        "A verifier",
        "A verifier",
        "A verifier (contact formation)",
        "CLOSING + IA : scripts de vente IA, pitch, traitement objections, emails relance, analyse LinkedIn. Complement ideal IA-Commerciaux. Pour conversions schoolsWP.",
        "A etudier en priorite - demander tarif/dates",
        "Complete cluster IA-Commerciaux (ligne 3)",
        "Tarif/sessions non affiches publiquement - appel CCI requis",
        "https://www.campus-moselle.cci.fr/formations/commercial/maitriser-les-fondamentaux-de-la-vente",
    ],
    [
        "13",
        "Les cles du marketing operationnel (+ IA)",
        "9/10 TRES HAUTE",
        "Priorite 1",
        "Nouvelle",
        "Marketing",
        "Presentiel ou visio",
        "Metz",
        "campus-moselle",
        "A verifier",
        "A verifier",
        "A verifier",
        "A verifier",
        "MARKETING + IA : 4P (prix/produit/promo/distrib), campagnes ciblees IA, A/B testing, emails/SMS/posts generes. Cœur metier schoolsWP.",
        "A etudier en priorite - demander tarif/dates",
        "Pas d'equivalent v1 (nouveau theme marketing)",
        "Tarif non affiche - appel CCI",
        "https://www.campus-moselle.cci.fr/formations/commercial/les-cles-du-marketing-operationnel",
    ],
    [
        "14",
        "TP Formateur Professionnel d'Adultes",
        "8/10 HAUTE",
        "Priorite 1",
        "Nouvelle - alternative v1#1",
        "RH / Formation",
        "Presentiel ou visio",
        "Metz",
        "campus-moselle",
        "Plusieurs mois (diplome)",
        "A verifier (formation longue)",
        "Diplome Ministere Travail (RNCP)",
        "A verifier",
        "ALTERNATIVE A CCE Formateur : titre pro RNCP du Ministere du Travail (plus prestigieux que CCE). 4 CCP : concevoir/animer/accompagner/evaluer.",
        "A comparer avec Formateur CCE (ligne 1) - choisir selon objectif diplome vs certif",
        "Doublon fonctionnel potentiel avec ligne 1",
        "Duree et tarif non affiches - comparer les 2 parcours",
        "https://www.campus-moselle.cci.fr/formations/ressources-humaines/tp-formateur-professionnel-dadultes",
    ],
    [
        "15",
        "Manager un projet - CCE",
        "8/10 HAUTE",
        "Priorite 2",
        "Nouvelle",
        "Management / Projet",
        "Presentiel ou visio",
        "Metz",
        "campus-moselle",
        "A verifier",
        "A verifier",
        "CCE",
        "A verifier",
        "Gestion de projet + conduite du changement + certification CCE. Utile pour structurer les lancements schoolsWP (pillar pages, produits, automatisations).",
        "A etudier - certifiante CCE",
        "Complete v1 (pas d'equivalent projet management)",
        "Tarif/sessions non affiches",
        "https://www.campus-moselle.cci.fr/formations/management/manager-un-projet-cce",
    ],
    [
        "16",
        "Communiquer efficacement",
        "7/10 HAUTE",
        "Priorite 2",
        "Nouvelle",
        "Communication",
        "Presentiel ou visio",
        "Metz",
        "campus-moselle",
        "A verifier",
        "A verifier",
        "Non",
        "A verifier",
        "Posture assertive, ecoute active, gestion conflits. Utile relation client premium schoolsWP + posture formateur.",
        "A confirmer - utile mais non essentielle",
        "Nouveau theme (communication)",
        "Tarif non affiche",
        "https://www.campus-moselle.cci.fr/formations/communication/communiquer-efficacement",
    ],
    [
        "17",
        "Bilan de competences Panorama",
        "7/10 HAUTE",
        "Priorite 2",
        "Nouvelle",
        "Developpement personnel",
        "Presentiel ou distance",
        "Metz",
        "campus-moselle (CIBC)",
        "24h sur plusieurs semaines",
        "A verifier (env. 1700-2400 EUR marche)",
        "Oui (CPF)",
        "Entrees permanentes",
        "Eligible CPF - positionnement entrepreneurial schoolsWP, validation trajectoire. Utile si questionnement strategique.",
        "A confirmer - CPF gratuit potentiel",
        "Nouveau theme",
        "Tarif a preciser avec CIBC Moselle",
        "https://www.campus-moselle.cci.fr/formations/developpement-personnel/bilan-de-competences-panorama",
    ],
    # --- NOUVELLES formations moselle.cci.fr (IA business-first) ---
    [
        "18",
        "Booster sa prospection commerciale avec l'IA",
        "10/10 ESSENTIELLE",
        "Priorite 1",
        "Nouvelle",
        "Intelligence artificielle / Vente",
        "A verifier",
        "Metz",
        "moselle.cci.fr",
        "A verifier",
        "A verifier",
        "A verifier",
        "A verifier",
        "🔥 CŒUR SCHOOLSWP : plan IA prospection, LinkedIn Sales Nav + IA, HubSpot IA, copywriting emails, Lemlist/Mailshake. Directement actionnable pour affiliations.",
        "A etudier en priorite - demander fiche complete",
        "Complete cluster IA (v1 #3) avec operationnel pointu",
        "Tarif/duree/sessions non affiches moselle.cci.fr - contact requis",
        "https://www.moselle.cci.fr/produit/booster-sa-prospection-commerciale-avec-lintelligence-artificielle",
    ],
    [
        "19",
        "Pilotez votre entreprise avec des tableaux de bord IA",
        "9/10 TRES HAUTE",
        "Priorite 1",
        "Nouvelle",
        "Intelligence artificielle / Pilotage",
        "A verifier",
        "Metz",
        "moselle.cci.fr",
        "A verifier",
        "A verifier",
        "A verifier",
        "A verifier",
        "🔥 KPI schoolsWP : detection tendances Excel+IA ou Power BI+Copilot, alertes sur seuils. Automatise le pilotage cashflow/trafic/conversion.",
        "A etudier en priorite",
        "Complete Excel TCD (v1 #5) niveau superieur",
        "Tarif/sessions a demander",
        "https://www.moselle.cci.fr/produit/pilotez-votre-entreprise-avec-des-tableaux-de-bord-de-gestion-intelligents-grace-lia",
    ],
    [
        "20",
        "Optimiser sa gouvernance avec l'IA",
        "8/10 HAUTE",
        "Priorite 2",
        "Nouvelle",
        "Intelligence artificielle / Strategie",
        "A verifier",
        "Metz",
        "moselle.cci.fr",
        "A verifier",
        "A verifier",
        "A verifier",
        "A verifier",
        "Posture dirigeant IA : ChatGPT/Copilot/Gamma/Napkin/Fathom, notes d'intention, plans d'action, analyse donnees. Complement IA-CODIR (v1 #2).",
        "A comparer avec IA-CODIR (ligne 2)",
        "Proche de ligne 2 - verifier si doublon",
        "Verifier le contenu exact vs IA-Dirigeants campus-moselle",
        "https://www.moselle.cci.fr/produit/optimiser-sa-gouvernance-avec-lintelligence-artificielle",
    ],
    [
        "21",
        "Optimiser son management avec l'IA",
        "6/10 MOYENNE",
        "Priorite 3",
        "Nouvelle",
        "Intelligence artificielle / Management",
        "A verifier",
        "Metz",
        "moselle.cci.fr",
        "A verifier",
        "A verifier",
        "A verifier",
        "A verifier",
        "Management ops avec IA, Power BI+IA, transcription. Utile si delegation.",
        "A surveiller - pas prioritaire solopreneur",
        "Proche de ligne 7 (IA-Managers)",
        "Doublon potentiel avec ligne 7",
        "https://www.moselle.cci.fr/produit/optimiser-son-management-avec-lintelligence-artificielle",
    ],
    [
        "22",
        "Developper la qualite au service du client - CCE",
        "7/10 HAUTE",
        "Priorite 2",
        "Nouvelle",
        "Relation client / Qualite",
        "A verifier",
        "Metz",
        "moselle.cci.fr",
        "A verifier",
        "A verifier",
        "CCE",
        "A verifier",
        "Ecoute active, IA pour analyser retours, indicateurs satisfaction, plan d'action QQOQCP. Utile pour support/onboarding schoolsWP + certif CCE.",
        "A etudier - certifiante CCE",
        "Nouveau theme (qualite/relation client)",
        "Tarif/sessions non affiches",
        "https://www.moselle.cci.fr/produit/developper-la-qualite-au-service-du-client-cce",
    ],
    [
        "23",
        "Bien vivre le changement",
        "5/10 MOYENNE",
        "Priorite 3",
        "Nouvelle",
        "Developpement personnel",
        "A verifier",
        "Metz",
        "moselle.cci.fr",
        "A verifier",
        "A verifier",
        "Non",
        "A verifier",
        "Resilience, adaptation aux transitions. Utile en complement mental/performance mais pas prioritaire.",
        "A surveiller",
        "Nouveau theme",
        "Tarif non affiche",
        "https://www.moselle.cci.fr/produit/bien-vivre-le-changement",
    ],
    [
        "24",
        "Le facteur mental - performance",
        "6/10 MOYENNE",
        "Priorite 2",
        "Nouvelle",
        "Developpement personnel / Performance",
        "A verifier",
        "Metz",
        "moselle.cci.fr",
        "A verifier",
        "A verifier",
        "Non",
        "A verifier",
        "Preparation mentale solopreneur : concentration, gestion stress, imagerie mentale, assertivite. Pertinent solo entrepreneur longue distance.",
        "A confirmer",
        "Complement v1 #9 (sante mentale) cote performance",
        "Tarif non affiche",
        "https://www.moselle.cci.fr/produit/le-facteur-mental-element-cle-de-la-performance",
    ],
]

# Add new tab
req = {
    "requests": [{"addSheet": {"properties": {"title": "v2", "gridProperties": {"rowCount": 60, "columnCount": 20}}}}]
}
try:
    svc.spreadsheets().batchUpdate(spreadsheetId=SHEET_ID, body=req).execute()
    print("Tab 'v2' created.")
except Exception as e:
    if "already exists" in str(e):
        print("Tab 'v2' already exists - will overwrite values.")
    else:
        raise

# Legend row at top, headers, rows
legend = [
    [
        "LEGENDE : Pertinence /10 (10=essentielle, 1=ecarter). Priorite 1 (immediat), 2 (cette annee), 3 (surveiller/ecarter). 'A verifier' = donnee non affichee publiquement - appeler CCI."
    ]
]
meta_row = [
    [
        "CCI Metz - Formations 2026 - schoolsWP v2 | Source v1 + scrape 2026-04-12 campus-moselle.cci.fr + moselle.cci.fr | Nancy non couverte par ces 2 sites (CCI 57 != CCI 54)"
    ]
]
body = {"values": meta_row + legend + [[""]] + [HEADERS] + ROWS}
svc.spreadsheets().values().update(spreadsheetId=SHEET_ID, range="v2!A1", valueInputOption="RAW", body=body).execute()

# Format: bold header row + freeze
sheet_id = None
for s in svc.spreadsheets().get(spreadsheetId=SHEET_ID).execute()["sheets"]:
    if s["properties"]["title"] == "v2":
        sheet_id = s["properties"]["sheetId"]
fmt_req = {
    "requests": [
        {
            "repeatCell": {
                "range": {"sheetId": sheet_id, "startRowIndex": 3, "endRowIndex": 4},
                "cell": {
                    "userEnteredFormat": {
                        "textFormat": {"bold": True},
                        "backgroundColor": {"red": 0.85, "green": 0.92, "blue": 1},
                    }
                },
                "fields": "userEnteredFormat(textFormat,backgroundColor)",
            }
        },
        {
            "updateSheetProperties": {
                "properties": {"sheetId": sheet_id, "gridProperties": {"frozenRowCount": 4}},
                "fields": "gridProperties.frozenRowCount",
            }
        },
    ]
}
svc.spreadsheets().batchUpdate(spreadsheetId=SHEET_ID, body=fmt_req).execute()
print(f"v2 written: {len(ROWS)} rows (11 existing + {len(ROWS) - 11} new)")
print("https://docs.google.com/spreadsheets/d/" + SHEET_ID + "/edit#gid=" + str(sheet_id))
