"""Generate the n8n inventory markdown report."""
import os
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "03-n8n-inventory.md"

parts = []

parts.append("# Etape 3 - Inventaire n8n\n\n")
parts.append("> Audit lecture seule via MCP n8n-mcp v2.51.3. Date : 2026-05-12.\n")
parts.append("> Instance : https://schoolswp-n8n.wp1.host\n")
parts.append("> Methode : n8n_audit_instance (built-in + custom scan 50+ regex) + n8n_list_workflows + n8n_manage_credentials.\n")
parts.append("> Aucune valeur secrete dans ce rapport.\n\n")
parts.append("---\n\n")

parts.append("## Resume executif\n\n")
parts.append("**377 findings totaux sur 65 workflows scannes** :\n\n")
parts.append("- **3 CRITIQUE** : secrets hardcodes detectes\n")
parts.append("- **10 ELEVE** : webhooks publics sans authentification sur workflows actifs\n")
parts.append("- **56 MOYEN** : erreurs handling absent + retention donnees + 4 emails hardcodes\n")
parts.append("- **308 FAIBLE** : retention executions excessive + nodes risque officiels (executeCommand etc.)\n\n")
parts.append("Constat marquants :\n\n")
parts.append("- **Instance n8n outdated** : 2.19.5 actuelle, 2.20.6 disponible (manque 1 update, peut contenir des CVE).\n")
parts.append("- **46 credentials stockees**, dont 29 inutilisees dans les 90 derniers jours (surface morte = vecteur d attaque).\n")
parts.append("- **216 nodes officiels potentiellement risques** scanned (executeCommand, HTTP avec injection, etc.).\n")
parts.append("- **3 community nodes** installes, non vetes par n8n.\n")
parts.append("- **publicApiEnabled = true** + **communityPackagesEnabled = true** + **telemetry diagnosticsEnabled = true**.\n")
parts.append("- **Aucun workflow ne touche FluentCart, Stripe, ou wp_update_post directement** sur le scope actif (donnees PII et financieres restent dans le perimetre WP).\n")
parts.append("- Mais : **3 workflows actifs ont des secrets hardcodes** (jwt_token, google_api_key) et **10 workflows actifs exposent des webhooks publics sans auth**.\n\n")

parts.append("---\n\n## 1. Etat global de l instance\n\n")
parts.append("| Metric | Valeur |\n|---|---|\n")
parts.append("| URL | https://schoolswp-n8n.wp1.host |\n")
parts.append("| Version n8n | 2.19.5 (latest 2.20.6, **a mettre a jour**) |\n")
parts.append("| Version MCP wrapper | 2.51.3 (a jour) |\n")
parts.append("| Total workflows | 65 |\n")
parts.append("| Actifs | 27 |\n")
parts.append("| Inactifs (non archives) | 17 |\n")
parts.append("| Archives | 21 |\n")
parts.append("| Total credentials | 46 |\n")
parts.append("| Credentials inutilisees recemment (>90j) | 29 |\n")
parts.append("| Findings totaux | 377 |\n\n")

parts.append("**Security settings n8n :**\n\n")
parts.append("- `communityPackagesEnabled` = true (permet d installer des nodes non-vetes, surface d attaque)\n")
parts.append("- `publicApiEnabled` = true (API publique active, ce qui permet ce meme audit, double tranchant)\n")
parts.append("- `telemetry.diagnosticsEnabled` = true (envoie des stats a n8n.io, fuite potentielle de noms de workflows)\n")
parts.append("- `templatesEnabled` = true (catalogue de templates utilisable)\n")
parts.append("- `nodesExclude` actif sur 4 nodes : executeCommand, localFileTrigger, e2eTest, dynamicCredentialCheck (**bon point** : nodes destructifs deja interdits)\n\n")

parts.append("---\n\n## 2. CRITIQUE - Secrets hardcodes (3)\n\n")
parts.append("| Workflow ID | Workflow | Node | Type secret | Status |\n|---|---|---|---|---|\n")
parts.append("| `BStRQkYKRv6VcRsf` | [InDev] LinkedIn Post > Claude: Prospecting Pipeline V4 | `Code: Validate Inputs & Auth` | jwt_token | **ACTIF** |\n")
parts.append("| `iXR2tvSfd5L9zE2t` | [Prod] Schedule > n8n: Workflows Backup | `Get All Workflows` | jwt_token | **ACTIF** |\n")
parts.append("| `nmXNUqXgmKVcrjsJ` | [InDev] Google Drive > Gemini: Organisateur Photos Vacances | `Analyser avec Gemini` | google_api_key | Inactif |\n\n")

parts.append("**Risque** :\n\n")
parts.append("- `iXR2tvSfd5L9zE2t` **Workflows Backup** est actif et stocke un jwt_token n8n-API en clair dans le node. Si le workflow est exporte (cf [Prod] Schedule > n8n: Workflows Backup qui justement exporte tous les workflows en JSON), le secret est dans le dump.\n")
parts.append("- `BStRQkYKRv6VcRsf` **Prospecting Pipeline V4** est actif **ET** expose un webhook public sans auth (voir section suivante). Combo : webhook public + jwt hardcoded dans le code = chemin d exploitation direct.\n")
parts.append("- `nmXNUqXgmKVcrjsJ` est inactif mais le google_api_key reste sur disque.\n\n")
parts.append("**Fix** (auto-fixable par le MCP n8n) :\n\n")
parts.append("1. `n8n_get_workflow` pour extraire la valeur.\n")
parts.append("2. `n8n_manage_credentials({action: 'create'})` pour creer une credential typee.\n")
parts.append("3. `n8n_update_partial_workflow` pour remplacer le secret par la reference credential.\n")
parts.append("4. Rotater le secret cote provider (jwt n8n + google_api_key) car deja stocke en clair = compromis par precaution.\n\n")

parts.append("---\n\n## 3. ELEVE - Webhooks publics sans authentification (10 actifs)\n\n")
parts.append("Tous les webhooks suivants sont **actifs en prod ou InDev** et acceptent des requetes anonymes. Un attaquant qui devine l URL peut declencher le workflow.\n\n")
parts.append("| Workflow ID | Workflow | Node webhook | Impact si exploite |\n|---|---|---|---|\n")
parts.append("| `BStRQkYKRv6VcRsf` | LinkedIn Post > Claude: Prospecting Pipeline V4 | Webhook: Receive Post URL | Trigger pipeline Claude (cout LLM) + jwt hardcoded expose |\n")
parts.append("| `WocLwnUAZPaZFitG` | Agent Orchestrator: Callback > Process Result | Webhook: Agent Callback | Empoisonnement de l orchestrator (false callbacks) |\n")
parts.append("| `krF2AcxO9sXBimLI` | Claude Skills > Google Sheets: Audit & Inventory Sync | Skills Audit Webhook | Triggers Google Sheets writes + Claude calls |\n")
parts.append("| `np4OG9UGDCGWaK4H` | Webhook > Discord: Tutor LMS Docs Watcher | Webhook PS1 receiver | Injection de notifications Discord arbitraires |\n")
parts.append("| `3JE0YzrhoiusJZ6T` | Webhook > Google Sheets: GEO Architect Bulk Fill | Webhook | Trigger ecritures Sheets + Claude calls |\n")
parts.append("| `Im1Khan3gJwhJkuu` | Webhook > Google Sheets: Thruuu Monitoring Results | Webhook | Pollution donnees Thruuu monitoring |\n")
parts.append("| `sLsPkcU3faV727dM` | YouTube > Kie.ai: Thumbnail Generator | webhook_trigger | Cout Kie.ai burn (videos) |\n")
parts.append("| `6utQzJcmXQczrHag` | Claude > Google Sheets: Skills Registry Sync | Webhook | Pollution registry skills + cout Claude |\n")
parts.append("| `CDuKpLL7E6LuaWNT` | Hub Drive > Auto Sync README Index | Webhook: On Demand | Trigger sync Drive + writes README |\n")
parts.append("| `MveNwfDlvVYYZTwz` | [Staging] Webhook: MIGRATION schoolswp | Webhook | Creation arborescence Drive arbitraire |\n\n")
parts.append("**Comment ils sont decouverts en pratique** :\n\n")
parts.append("- URL n8n webhooks suit le pattern `https://schoolswp-n8n.wp1.host/webhook/<uuid>` ou `/webhook-test/<uuid>`.\n")
parts.append("- Si une URL fuite dans un repo public ou un transcript (Telegram, n8n exports, captures d ecran), elle est expoitable directement.\n")
parts.append("- Pas de protection IP. Pas de signature. Pas de rate limit n8n natif.\n\n")
parts.append("**Fix** (auto-fixable par le MCP) :\n\n")
parts.append("1. Pour chaque webhook : `n8n_manage_credentials({action: 'create', type: 'httpHeaderAuth'})` avec un secret random.\n")
parts.append("2. `n8n_update_partial_workflow` pour configurer `authentication: 'headerAuth'` sur le node Webhook.\n")
parts.append("3. Cote consumer (ce qui appelle le webhook) : mettre a jour avec l en-tete d auth.\n\n")
parts.append("**Cas particulier** : pour les webhooks qui recoivent des callbacks de SaaS tiers (Skoatch, HeyGen, etc.) qui n acceptent pas custom headers, mettre une signature HMAC dans la payload + verifier dans le node Code juste apres.\n\n")

parts.append("---\n\n## 4. MOYEN - Emails hardcodes dans 4 workflows\n\n")
parts.append("| Workflow ID | Workflow | Node | Email |\n|---|---|---|---|\n")
parts.append("| `PkFO7Of9BrMfl8Ed` | [InDev] Google Drive Auto-Rename on Move | Alert Email | (a verifier) |\n")
parts.append("| `RQZnUp6C1qC82Q7K` | [InDev] Schedule > Pinterest | Envoyer Notification | (a verifier) |\n")
parts.append("| `ls46UbBJJuZCobfI` | [InDev] YouTube schoolsWP Analyse | Gmail Notification | (a verifier) |\n")
parts.append("| `NZMJOfiaNPqyAajd` | [Prod] WP Articles Content Fill v5 | Send a message | (a verifier) |\n\n")
parts.append("Faible criticite mais polluant pour le RGPD si l email est celui d un tiers. A externaliser en credential ou variable d environnement n8n.\n\n")

parts.append("---\n\n## 5. Credentials stockees (46)\n\n")
parts.append("### Inventaire par usage\n\n")
parts.append("**Top 5 les plus utilisees** :\n\n")
parts.append("| Credential | Type | Workflows | Notes |\n|---|---|---|---|\n")
parts.append("| Google Sheets - schoolsWP v2 | googleSheetsOAuth2 | 28 | colonne vertebrale data des workflows |\n")
parts.append("| Anthropic account | anthropicApi | 12 | duplique avec Anthropic_Production_ApiKey (3) = **consolider** |\n")
parts.append("| Google Drive - schoolsWP v2 | googleDriveOAuth2 | 11 | |\n")
parts.append("| Gmail - schoolsWP | gmailOAuth2 | 8 | duplique avec Gmail - schoolsWP v2 (1) = a unifier |\n")
parts.append("| n8n - schoolsWP (OpenAI) | openAiApi | 8 | |\n\n")

parts.append("**Credentials orphelines (usageCount = 0) - 17 trouvees** :\n\n")
parts.append("- `DataForSEO_Production_BasicAuth` (cree 2026-05-07, jamais utilisee, **a supprimer**)\n")
parts.append("- `SerpApi`, `Exa.AI`, `Wisewand`, `Brevo`, `Perplexity`, `Slack account`\n")
parts.append("- `Gemini_Production_API`, `Google Gemini(PaLM) Api account` (doublon Gemini)\n")
parts.append("- `Google Analytics - schoolsWP v2`, `Google Calendar - schoolsWP v2`, `Google Contacts - schoolsWP v2`\n")
parts.append("- `Google Sheets Trigger - schoolsWP`, `Google BigQuery - schoolsWP`, `YouTube - schoolsWP`\n")
parts.append("- `Agent Orchestrator Callback`, `Thruuu Monitoring Results`, `GEO Architect Bulk Fill`\n")
parts.append("- `QdrantApi - schoolsWP`\n\n")
parts.append("Toutes ces credentials :\n\n")
parts.append("1. **Auraient pu etre utilisees par un workflow qui n est plus actif**. Si oui, la credential reste valide cote provider mais sans usage = surface morte. Recommandation : supprimer la credential cote n8n + rotater la cle cote provider si elle a > 90 jours.\n")
parts.append("2. **Doublons clairs a consolider** :\n")
parts.append("    - Anthropic_Production_ApiKey + Anthropic account = un seul\n")
parts.append("    - Gemini_Production_API + Google Gemini(PaLM) Api account = un seul\n")
parts.append("    - Gmail - schoolsWP + Gmail - schoolsWP v2 = un seul\n")
parts.append("    - Google Drive - schoolsWP + Google Drive - schoolsWP v2 = un seul\n")
parts.append("    - Google Docs - schoolsWP + Google Docs - schoolsWP v2 = un seul\n\n")
parts.append("Apres consolidation, ~10 credentials a supprimer (estimation).\n\n")

parts.append("---\n\n## 6. Nodes risques\n\n")
parts.append("**216 nodes officiels risques** ont ete detectes (HTTP Request, Code/Function, jsonata, etc.) qui peuvent fetcher et executer du code arbitraire. Le `nodesExclude` actuel bloque 4 nodes (executeCommand, localFileTrigger, e2eTest, dynamicCredentialCheck) : bon point.\n\n")
parts.append("**3 community nodes** installes. Non identifies dans l audit, mais a verifier dans n8n UI > Settings > Community Nodes. Risque : code tiers non vete avec acces complet a l instance.\n\n")

parts.append("---\n\n## 7. Findings classes\n\n")
parts.append("### CRITIQUE\n\n")
parts.append("1. **3 secrets hardcodes dans des workflows**\n")
parts.append("   2 jwt_token (workflows actifs) + 1 google_api_key (workflow inactif). Auto-fixable via n8n_manage_credentials.\n\n")
parts.append("2. **n8n outdated v2.19.5**\n")
parts.append("   Manque 1 update vers 2.20.6 qui peut contenir des CVE. Update via xCloud panel ou commande directe.\n\n")
parts.append("3. **N8N_ENCRYPTION_KEY en clair dans systems/n8n/.env**\n")
parts.append("   Deja note a l etape 1. Cle maitre qui chiffre toutes les 46 credentials stockees. Compromission = decryption complete.\n\n")

parts.append("### ELEVE\n\n")
parts.append("4. **10 webhooks publics sans authentification sur workflows actifs**\n")
parts.append("   Voir section 3. Auto-fixable via httpHeaderAuth + secret random.\n\n")
parts.append("5. **publicApiEnabled = true**\n")
parts.append("   L API publique n8n est ouverte. Indispensable pour ce MCP, mais expose une surface qui doit etre protegee derriere Cloudflare Access (etape 7 du briefing).\n\n")
parts.append("6. **communityPackagesEnabled = true + 3 community nodes installes**\n")
parts.append("   Verifier quels packages sont actifs et leur reputation.\n\n")
parts.append("7. **29 credentials non-utilisees > 90 jours**\n")
parts.append("   Tokens valides cote provider mais zero usage cote n8n. Supprimer + rotater (auto- ou semi-auto via n8n_manage_credentials).\n\n")
parts.append("8. **Aucune politique de retention executions configuree**\n")
parts.append("   10 workflows flagges. Les payloads des executions (qui peuvent contenir PII via Gmail/FluentCRM/etc.) sont retenus indefiniment. Configurer dans n8n Settings > Executions.\n\n")
parts.append("9. **n8n basic auth password en clair dans systems/n8n/.env**\n")
parts.append("   Deja note etape 1.\n\n")

parts.append("### MOYEN\n\n")
parts.append("10. **48 workflows sans error handling**\n")
parts.append("    Pas d Error Trigger node. Les erreurs partent en silence ou en email Owner par defaut. Ajouter au minimum une notification Telegram/Discord sur les workflows critiques.\n\n")
parts.append("11. **4 emails hardcodes dans des nodes**\n")
parts.append("    Section 4. Faible mais pollue le RGPD.\n\n")
parts.append("12. **Doublons de credentials (Anthropic x2, Gmail x2, Drive x2, Docs x2, Gemini x2)**\n")
parts.append("    Source de confusion + rotation manquee si on ne rote qu une des deux. Consolider.\n\n")
parts.append("13. **17 workflows inactifs non archives**\n")
parts.append("    Bruit cognitif. Soit reactiver, soit archiver (`isArchived=true`).\n\n")
parts.append("14. **telemetry.diagnosticsEnabled = true**\n")
parts.append("    Stats envoyees a n8n.io. Pas critique mais leak de meta-info (noms workflows). A desactiver si paranoid.\n\n")

parts.append("### FAIBLE\n\n")
parts.append("15. **Retention executions excessive sur 10 workflows**\n")
parts.append("    Lie a #8. Faible parce que pas de PII massive, mais a nettoyer.\n\n")
parts.append("16. **21 workflows archives**\n")
parts.append("    Hygiene normale. A purger periodiquement si tu n y reviens jamais.\n\n")

parts.append("---\n\n## 8. Workflows actifs : analyse par criticite\n\n")
parts.append("**Workflows actifs qui touchent l infra schoolswp.com** (mutations potentielles) :\n\n")
parts.append("- `DcbnlLoedzX2lVIJ` [Staging] WordPress > Google Sheets: Sync & Classify Blog Posts (lecture seule WP -> ecriture Sheets)\n")
parts.append("- `NZMJOfiaNPqyAajd` [Prod] WP Articles > Google Docs: Content Fill v5 (lecture WP -> ecriture Docs)\n")
parts.append("- `RQZnUp6C1qC82Q7K` [InDev] Schedule > Pinterest: Auto-Generate Pins on New Article (lecture WP -> ecriture Pinterest)\n")
parts.append("- `ktrlXAI5szH3lr8F` [Prod] Sheets > AI Agents: Veille Plugins schoolsWP W206 (Firecrawl + Sheets)\n")
parts.append("- `iXR2tvSfd5L9zE2t` [Prod] Schedule > n8n: Workflows Backup (lit tous workflows + jwt_token hardcoded)\n\n")
parts.append("**Bon point** : aucun workflow ne fait wp_update_post / wp_insert_post / FluentCart mutations / Stripe ops. Les mutations WP critiques restent dans WP (mu-plugins + dashboard admin + Novamira MCP execute-php quand actif).\n\n")
parts.append("**Workflows agents tres lies a Claude API (cout LLM)** :\n\n")
parts.append("- 12 workflows actifs utilisent la credential `Anthropic account`. Un attaquant qui controle un webhook public peut burn ton credit Anthropic.\n")
parts.append("- Aucun spend limit n8n natif. Mitigation : limit cote Anthropic Console + monitoring usage quotidien.\n\n")

parts.append("---\n\n## 9. Recommandations actionnables\n\n")
parts.append("### A faire en 1 session focus n8n (estimation 2-3 heures)\n\n")
parts.append("1. **Update n8n vers 2.20.6** (via xCloud panel) - 10 min\n")
parts.append("2. **Auto-fix 3 hardcoded secrets** via le MCP (creer credentials, remplacer dans nodes, rotater cote provider) - 30 min\n")
parts.append("3. **Auto-fix 10 webhooks publics** en ajoutant httpHeaderAuth a chacun - 1h\n")
parts.append("4. **Supprimer 17 credentials orphelines** (apres avoir verifie qu aucun workflow inactif ne les utilise) - 20 min\n")
parts.append("5. **Consolider 5 doublons de credentials** (Anthropic, Gmail, Drive, Docs, Gemini) - 20 min\n")
parts.append("6. **Archiver 17 workflows inactifs non archives** - 5 min\n\n")
parts.append("### A faire en suivi (semaine 2)\n\n")
parts.append("7. **Cloudflare Access devant l UI n8n** (etape 7 briefing) - retire l acces public au panel n8n.\n")
parts.append("8. **Configurer execution data pruning** dans n8n Settings (max 7-14 jours).\n")
parts.append("9. **Mettre n8n derriere un firewall qui restreint /webhook/* a Cloudflare IPs** + rate limit Cloudflare sur ces routes.\n")
parts.append("10. **Audit des 3 community nodes installes** (n8n UI > Settings).\n")
parts.append("11. **Spend limit Anthropic dedie au workflow `BStRQkYKRv6VcRsf`** + alerte si depasse seuil.\n\n")

parts.append("### Bloqueurs sans modification\n\n")
parts.append("- L upgrade n8n peut casser des workflows si breaking changes (rare entre patches mineurs). A faire un samedi avec un rollback xCloud snapshot prepret.\n")
parts.append("- Ajouter auth aux webhooks publics impose de mettre a jour les consumers (apps schoolswp-agents Mac, autres workflows, Skoatch, etc.). Mapping precis a faire avant.\n\n")

parts.append("## Etape 3 terminee. En attente validation pour etape 4 (secrets multi-niveaux).\n")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("".join(parts), encoding="utf-8")
print(f"WRITTEN: {OUT} ({OUT.stat().st_size} bytes)")
