"""Helper to write the recon inventory report from a list of plain-text parts (no markdown command backticks)."""
import os
import sys

PARTS = []

PARTS.append("# Etape 1 - Inventaire PC dev (Windows 11)\n\n")
PARTS.append("> Audit lecture seule. Date : 2026-05-12. Plateforme : Windows 11 Home, PC ROG Strix SCAR 16, user conta.\n")
PARTS.append("> Aucune modification effectuee. Aucun secret en clair dans ce rapport (4 derniers chars max si necessaire).\n\n")
PARTS.append("---\n\n")
PARTS.append("## Resume executif\n\n")
PARTS.append("5 findings CRITIQUE, 6 findings ELEVE, 5 findings MOYEN, 3 findings FAIBLE.\n\n")
PARTS.append("Le perimetre dev est riche mais fortement fragmente :\n\n")
PARTS.append("- ~14 fichiers .env contenant des secrets reels (hors .example), repartis sur 4 sous-systemes (root, n8n, fleet schoolswp-agents, apps annexes, archives).\n")
PARTS.append("- Memes secrets dupliques dans plusieurs fichiers (blast radius x4 sur ANTHROPIC_API_KEY notamment).\n")
PARTS.append("- .mcp.json.bak et .mcp.backup.json du 27-28 avril 2026, identiques byte-a-byte, encore presents sur disque alors qu anterieurs aux rotations documentees.\n")
PARTS.append("- Windows Defender real-time protection OFF (offset par Kaspersky, a confirmer).\n")
PARTS.append("- C:/Users/conta/bin en tete de PATH (vecteur PATH hijack).\n\n")
PARTS.append("La rotation prioritaire et la migration vers vault central (etapes 4, 7, 8 du briefing) sont indispensables. Le pipeline de hardening peut demarrer des que ces bases sont posees.\n\n")
PARTS.append("---\n\n")

PARTS.append("## 1. Process longs\n\n")
PARTS.append("Capture instantanee, processus dev en cours :\n\n")
PARTS.append("| Process | Count |\n|---|---|\n")
PARTS.append("| node | 85 |\n| claude | 14 |\n| docker (toutes variantes) | 19 |\n| python | 6 |\n| pwsh | 1 |\n\n")
PARTS.append("Lecture : 85 processus node simultanes correspondent aux ~28 MCP servers + Claude Code stdio enfants + agents fleet. 14 instances claude = main + 4 fleet schoolswp-agents + ~9 sous-process / worktrees. Pas d anomalie immediate, mais surface memoire et complexite elevees.\n\n")

PARTS.append("## 2. Venvs Python\n\n")
PARTS.append("4 venvs detectes :\n\n")
PARTS.append("- .venv/ (workspace root, prod schoolsWP)\n")
PARTS.append("- apps/claude-telegram-poc/venv/ (POC, a archiver ?)\n")
PARTS.append("- systems/multi-agent-system/multi-agent-system/.venv/ (dossier duplique imbrique, anomalie connue cf CLAUDE.md)\n")
PARTS.append("- .claude/skills/external-video-use/.venv/ (skill externe, isole)\n\n")
PARTS.append("Aucun venv dans worktrees Git ou _archive/. Bon point.\n\n")

PARTS.append("## 3. Fichiers .env (KEYS uniquement, jamais les valeurs)\n\n")
PARTS.append("14 .env reels (hors .example et .backup.example), 132 variables au total.\n\n")
PARTS.append("| Fichier | Vars | Note |\n|---|---|---|\n")
PARTS.append("| .env (root) | 27 | LLM/social/n8n hub |\n")
PARTS.append("| systems/n8n/.env | 52 | n8n prod (DB postgres + S3 + basic auth) |\n")
PARTS.append("| agents/telegram-claude/.env | 17 | 6 Telegram bot tokens FLOW/PULSE/RADAR/REDDIT/STUDIO/WELCOME + Discord |\n")
PARTS.append("| systems/multi-agent-system/multi-agent-system/.env | 13 | sous-systeme multi-agent (dossier duplique) |\n")
PARTS.append("| agents/.env | 6 | Hunter + Unipile + N8N_WEBHOOK_SECRET |\n")
PARTS.append("| apps/claude-telegram-poc/.env | 5 | POC isole |\n")
PARTS.append("| apps/_archive/elearning/elearning/elearning/.env | 5 | ARCHIVE, a verifier |\n")
PARTS.append("| apps/_archive/telegram-bot-legacy/.env | 2 | ARCHIVE, a verifier |\n")
PARTS.append("| tools/skoatch/.env | 1 | SKOATCH_TOKEN |\n")
PARTS.append("| .claude/skills/external-video-use/.env | 1 | ELEVENLABS_API_KEY |\n")
PARTS.append("| schoolswp-agents/(content-studio|seo-geo|crm-automation|social-community)/.claude/channels/telegram/.env | 4 x 1 | TELEGRAM_TOKEN fleet |\n\n")

PARTS.append("Doublons critiques (meme secret dans plusieurs fichiers) :\n\n")
PARTS.append("| Variable | Presence | Blast radius si leake |\n|---|---|---|\n")
PARTS.append("| ANTHROPIC_API_KEY | .env, agents/.env, agents/telegram-claude/.env, multi-agent-system/.env | 4x |\n")
PARTS.append("| OPENAI_API_KEY | .env, systems/n8n/.env | 2x |\n")
PARTS.append("| FIRECRAWL_API_KEY | .env, agents/.env | 2x |\n")
PARTS.append("| ELEVENLABS_API_KEY | .env, .claude/skills/external-video-use/.env | 2x |\n")
PARTS.append("| Discord bot tokens + channels | .env, agents/telegram-claude/.env | 2x |\n\n")

PARTS.append("Cles sensibles infrastructure (n8n) :\n\n")
PARTS.append("systems/n8n/.env contient en clair :\n\n")
PARTS.append("- N8N_BASIC_AUTH_PASSWORD (gardien de l UI n8n)\n")
PARTS.append("- N8N_ENCRYPTION_KEY (cle maitre qui chiffre TOUTES les credentials stockees dans n8n)\n")
PARTS.append("- DB_POSTGRESDB_PASSWORD (DB prod n8n)\n")
PARTS.append("- S3_SECRET_KEY (backups n8n cote S3)\n")
PARTS.append("- WHATSAPP_CALLMEBOT_APIKEY\n")
PARTS.append("- DATAFORSEO_PASSWORD\n\n")
PARTS.append("Le N8N_ENCRYPTION_KEY est de loin le plus critique : un attaquant qui l obtient peut dechiffrer toutes les credentials cumulees dans n8n (ce qui inclut les credentials FluentCart, Stripe, et toute la stack OAuth Google).\n\n")

PARTS.append("## 4. Settings Claude Code\n\n")
PARTS.append("| Fichier | Bytes | Env blocks | Uppercase KEY entries |\n|---|---|---|---|\n")
PARTS.append("| .claude/settings.local.json (workspace) | 85 418 | 1 | 18 |\n")
PARTS.append("| C:/Users/conta/.claude/settings.local.json (user) | 264 | 0 | 0 |\n")
PARTS.append("| C:/Users/conta/.claude/settings.json (user) | 12 013 | 0 | 0 |\n\n")
PARTS.append("Secrets dans .claude/settings.local.json (workspace) :\n\n")
PARTS.append("APIFY_TOKEN, DATAFORSEO_PASSWORD, DATAFORSEO_USERNAME, DISCORD_BOT_TOKEN, FIRECRAWL_API_KEY, FLUENTCRM_API_PASSWORD, FLUENTCRM_API_URL, FLUENTCRM_API_USERNAME, GEMINI_API_KEY, GITHUB_TOKEN, N8N_API_KEY, N8N_API_URL, RAPIDAPI_KEY, WISEWAND_API_KEY, WP_API_PASSWORD, WP_API_URL, WP_API_USERNAME, ZIPWP_TOKEN\n\n")
PARTS.append("Pattern coherent avec la memoire reference_claude_code_secrets_storage : les MCP lisent depuis ce fichier via launcher .mjs. Mais ces secrets sont aussi presents dans .env workspace et agents/.env pour certains (FIRECRAWL_API_KEY, APIFY_TOKEN, GEMINI_API_KEY, DISCORD_BOT_TOKEN, GITHUB_TOKEN, RAPIDAPI_KEY...). Source de verite ambigue.\n\n")

PARTS.append("## 5. .mcp.json variants\n\n")
PARTS.append("| Fichier | Date | Bytes | VAR refs | Suspect long strings | Notes |\n|---|---|---|---|---|---|\n")
PARTS.append("| .mcp.json | 11 mai 2026 | 5 997 | 9 | 27 | actif, pattern launcher |\n")
PARTS.append("| .mcp.json.bak | 28 avril 2026 | 5 191 | 27 | 36 | suspect, identique au backup |\n")
PARTS.append("| .mcp.backup.json | 27 avril 2026 | 5 191 | 27 | 36 | identique a .bak, contient VAR substitution massive |\n")
PARTS.append("| .mcp.json.fluent | 29 avril 2026 | 2 043 | 1 | 7 | snapshot config Fluent |\n")
PARTS.append("| .mcp.json.example | 6 mai 2026 | 3 002 | 1 | 21 | template git-tracke |\n\n")
PARTS.append("Les long-strings dans .mcp.json.bak et .mcp.backup.json meritent une inspection rapprochee : les 27 VAR substitutions indiquent que le pattern variable-substitution etait en place, mais 36 strings de plus de 20 chars sans VAR peuvent etre des URLs, des noms de packages npm, OU des secrets residuels pre-rotation 2026-04-21 / 2026-04-29 documentees. Aucune reference 1Password CLI (op://) a ce jour.\n\n")

PARTS.append("## 6. Cles SSH\n\n")
PARTS.append("C:/Users/conta/.ssh/\n\n")
PARTS.append("- config (167 octets, a examiner)\n")
PARTS.append("- known_hosts (926 octets)\n")
PARTS.append("- known_hosts.old (94 octets)\n")
PARTS.append("- telegram_agents_wp1 (cle privee ED25519, 432 octets)\n")
PARTS.append("- telegram_agents_wp1.pub : SHA256:xiIx15i7gQIyoGjeiNzw15jV2ZFKjrGfyvVRpTlT6SM (telegram_agents@schoolswp-20260419)\n\n")
PARTS.append("1 seule cle privee, dediee au deploiement telegram-agents WP1 (xCloud). Pas de cle GitHub locale (cf insteadOf du .gitconfig qui route SSH vers HTTPS, deja documente en memoire).\n\n")
PARTS.append("Statut passphrase non testable depuis ici (le classifier a bloque la probe sur cle privee, comportement sain). A verifier manuellement par Michael avec un test passphrase vide dans une session separee (silence sans erreur = pas de passphrase = CRITIQUE).\n\n")

PARTS.append("## 7. PATH analysis\n\n")
PARTS.append("Entrees writable par conta listees dans l ordre du PATH :\n\n")
PARTS.append("| Position | Path | Risque |\n|---|---|---|\n")
PARTS.append("| 1 (top) | C:/Users/conta/bin | CRITIQUE : user-writable, AVANT System32 |\n")
PARTS.append("| 9 | D:/VS Code/CLAUDE CODE/projects/schoolswp/.venv/Scripts | ELEVE : projet schoolswp prend precedence (intentionnel mais risque si compromis) |\n")
PARTS.append("| 24 | C:/Users/conta/.bun/bin | MOYEN |\n")
PARTS.append("| 25 | C:/Users/conta/.local/bin | MOYEN |\n")
PARTS.append("| 27 | C:/Users/conta/AppData/Local/Microsoft/WindowsApps | MOYEN |\n")
PARTS.append("| 29 | C:/Users/conta/AppData/Local/Python/bin | MOYEN |\n")
PARTS.append("| 30 | C:/Users/conta/AppData/Roaming/npm | MOYEN |\n")
PARTS.append("| 31 | C:/Users/conta/AppData/Local/Microsoft/WinGet/Packages/Ngrok.Ngrok_* | FAIBLE |\n")
PARTS.append("| 32 | C:/Users/conta/AppData/Local/Microsoft/WinGet/Packages/Cloudflare.cloudflared_* | FAIBLE |\n")
PARTS.append("| 34 | C:/users/conta/appdata/roaming/python/python314/scripts | MOYEN (casse mixte) |\n")
PARTS.append("| 35 | C:/Users/conta/AppData/Local/Programs/Antigravity/bin | MOYEN |\n")
PARTS.append("| 38 | C:/Users/conta/AppData/Local/Programs/ExifTool | FAIBLE (cf memory reference_exiftool_path) |\n")
PARTS.append("| 39 | C:/Users/conta/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin | MOYEN |\n")
PARTS.append("| 40 | C:/Users/conta/go/bin | MOYEN |\n\n")
PARTS.append("Doublons dans PATH (a nettoyer pour proprete) : C:/Program Files/Git/usr/bin et C:/Program Files/Git/mingw64/bin listes 2x chacun.\n\n")

PARTS.append("## 8. Containers Docker\n\n")
PARTS.append("3 containers brightbean-studio-* exited il y a 2 semaines (residu, a nettoyer).\n")
PARTS.append("1 container openshell-cluster-nemoclaw running depuis 30h sur port 8080 = legit (cf memoire project_nemoclaw_setup).\n\n")
PARTS.append("Networks : 5 (bridge, host, none, brightbean-studio_default residu, openshell-cluster-nemoclaw).\n\n")
PARTS.append("PM2 absent localement = les apps PM2 (telegram-agents, discord-orchestrator) tournent uniquement sur xCloud.\n\n")

PARTS.append("## 9. Caches credentials et identites tierces\n\n")
PARTS.append("- D:/.../projects/schoolswp/.credentials/gsc-client-secrets.json (398 octets, OAuth Google Search Console, deja gitignored).\n")
PARTS.append("- C:/Users/conta/.docker/config.json (403 octets, credsStore actif, Docker pousse les creds vers Credential Manager).\n")
PARTS.append("- C:/Users/conta/.gitconfig (1 225 octets, 16 safe.directory dont 2 doublons michaelkihl-fr).\n")
PARTS.append("- C:/Users/conta/.npmrc : ABSENT (bonne nouvelle, pas de _authToken qui traine).\n")
PARTS.append("- C:/Users/conta/.aws/ : vide (pas d AWS credentials).\n")
PARTS.append("- gh CLI : 2 comptes authentifies sous kihlmichael (un via env GITHUB_TOKEN, un via keyring). Token actif = env. Scopes : read:org, read:user, repo, workflow. Format classic PAT, pas fine-grained.\n")
PARTS.append("- Windows Credential Manager : Microsoft 365 SSO contact@michaelkihl.fr, Adobe (App Info), Docker Hub access+refresh tokens, gh kihlmichael keyring, docker/mcp/SHODAN_API_KEY. Aucun secret WP Umbrella detecte alors que la memoire reference_wp_umbrella_skill indique qu il devrait y etre. A investiguer.\n\n")

PARTS.append("## 10. Taches planifiees + services tiers\n\n")
PARTS.append("Taches planifiees non-Microsoft enabled (toutes legit) :\n")
PARTS.append("Adobe (Acrobat Update, Genuine Software Integrity, AdobeGCInvoker, Launch CCXProcess), ASUS x9 (AcPower, ArmourySocketServer, GearLink x5, P508PowerAgent), NVIDIA App SelfUpdate + Shader Compiler, OneDrive x3, Samsung_PSSD_Registration, ZoomUpdateTaskUser. Aucune tache custom dev/cron.\n\n")
PARTS.append("Services tiers running auto :\n")
PARTS.append("Kaspersky (AVP21.24 antivirus + KSDE5.25 VPN + kpm_service Password Manager), Adobe (ARM + Update), ASUS x9 (Armoury Crate, ScreenXpert, GlideX x3, Aura Wallpaper, GameSDK, ROG Live Service, MS Control, AsusCertService), NVIDIA NvContainer LocalSystem, WSL Service, Office ClickToRun, Microsoft Defender (mais real-time desactive, cf section 11), Claude CoworkVMService (cowork-svc depuis app Claude Windows native).\n\n")
PARTS.append("WSL2 disponible (service running) = option viable pour proxy sortant agents (Privoxy ou squid, recommandation briefing etape 10).\n\n")

PARTS.append("## 11. Windows Defender + AV\n\n")
PARTS.append("    AMServiceEnabled              : True\n")
PARTS.append("    AntivirusEnabled              : True\n")
PARTS.append("    RealTimeProtectionEnabled     : False    <-- OFF\n")
PARTS.append("    IoavProtectionEnabled         : False    <-- OFF\n")
PARTS.append("    BehaviorMonitorEnabled        : False    <-- OFF\n")
PARTS.append("    OnAccessProtectionEnabled     : False    <-- OFF\n")
PARTS.append("    TamperProtected               : (vide)\n")
PARTS.append("    AntivirusSignatureLastUpdated : 12/05/2026 01:15:03\n")
PARTS.append("    QuickScanAge                  : 0\n")
PARTS.append("    FullScanAge                   : 4294967295 (jamais)\n\n")
PARTS.append("Defender est en mode passif parce que Kaspersky 21.24 a pris le relais comme AV principal (AVP21.24, KSDE5.25, kpm_service_25.1). Comportement normal sous Windows 11. Threat detection history Defender : vide. Pas d evidence d infection courante.\n\n")
PARTS.append("Action requise : confirmer que Kaspersky est licencie, a jour, et que le real-time scan est actif cote Kaspersky (a verifier dans Kaspersky UI).\n\n")

PARTS.append("---\n\n## Findings classes\n\n")

PARTS.append("### CRITIQUE\n\n")
PARTS.append("1. N8N_ENCRYPTION_KEY en clair dans systems/n8n/.env\n")
PARTS.append("   Cle maitre qui chiffre toutes les credentials stockees dans n8n (FluentCart, Stripe, Google OAuth, etc.). Compromission = compromission cascade de toute la stack n8n. Rotation immediate ET migration vault a prioriser absolument.\n\n")
PARTS.append("2. ANTHROPIC_API_KEY duplique dans 4 fichiers .env\n")
PARTS.append("   Blast radius x4. Un seul leak compromet la facturation Anthropic complete et donne acces a tous les agents. Migration vault avec une cle par machine (briefing etape 7 et 9).\n\n")
PARTS.append("3. .mcp.json.bak et .mcp.backup.json identiques byte-a-byte du 27-28 avril 2026\n")
PARTS.append("   Anterieurs aux rotations RapidAPI documentees (incident 2026-04-21) et Fluent (2026-04-29). Probable contiennent des secrets rotates mais non purges. A examiner et supprimer manuellement via Explorer.\n\n")
PARTS.append("4. C:/Users/conta/bin premier dans PATH\n")
PARTS.append("   Vecteur PATH hijack : tout executable malicieux depose la est lance avant ceux de System32. Soit deplacer en fin de PATH, soit auditer son contenu et le passer en read-only.\n\n")
PARTS.append("5. 6 Telegram bot tokens en clair dans agents/telegram-claude/.env\n")
PARTS.append("   FLOW, PULSE, RADAR, REDDIT, STUDIO, WELCOME. Pas de rotation possible sans casser les bots (memoire confirme), donc le stockage doit etre verrouille. Migration vault prioritaire + restriction d acces filesystem.\n\n")

PARTS.append("### ELEVE\n\n")
PARTS.append("6. Statut passphrase de la cle SSH telegram_agents_wp1 non verifie\n")
PARTS.append("   Si pas de passphrase = perte du PC = acces direct a l instance WP1 xCloud. A verifier manuellement par Michael (test passphrase vide dans une session separee, silence sans erreur = pas de passphrase).\n\n")
PARTS.append("7. PAT GitHub actif avec scopes large\n")
PARTS.append("   repo + workflow + read:org = peut push, peut alterer GitHub Actions, peut lire l organisation. Stocke a 2 endroits (env + keyring). A migrer en fine-grained PAT par usage.\n\n")
PARTS.append("8. 2 comptes GitHub kihlmichael simultanement actifs dans gh CLI\n")
PARTS.append("   Confusion d identite. Consolider en un seul (le keyring est plus sur que l env).\n\n")
PARTS.append("9. Windows Defender real-time OFF\n")
PARTS.append("   Compense par Kaspersky, mais necessite confirmation que Kaspersky est sous licence active et en real-time scan. Sinon, breche silencieuse.\n\n")
PARTS.append("10. Settings.local.json workspace 85 KB avec 18 secrets\n")
PARTS.append("    Concentration forte = single point of failure. La migration vers 1Password CLI (briefing etape 8) doit etre prioritaire.\n\n")
PARTS.append("11. 2 .env dans apps/_archive/\n")
PARTS.append("    telegram-bot-legacy/.env et elearning/elearning/elearning/.env. Archives donc oublies. Auditer ce qu ils contiennent (probablement des secrets pre-rotation) puis supprimer manuellement.\n\n")

PARTS.append("### MOYEN\n\n")
PARTS.append("12. Dossier systems/multi-agent-system/multi-agent-system/ duplique imbrique\n")
PARTS.append("    Anomalie documentee dans CLAUDE.md. Son .env contient 13 vars dont ANTHROPIC_API_KEY. Auditer si encore utilise, sinon archiver.\n\n")
PARTS.append("13. Containers brightbean-studio-* exited il y a 2 semaines\n")
PARTS.append("    Residu, a supprimer apres confirmation Michael.\n\n")
PARTS.append("14. PATH doublons : Git/usr/bin et mingw64/bin listes 2x chacun. Cosmetique mais signal d un PATH non maintenu.\n\n")
PARTS.append("15. gitconfig doublons : michaelkihl-fr liste 2x en safe.directory. A nettoyer.\n\n")
PARTS.append("16. docker/mcp/SHODAN_API_KEY dans Credential Manager\n")
PARTS.append("    Token Shodan dans Docker MCP credential store. Verifier si Docker MCP est activement utilise. Si non, retirer.\n\n")

PARTS.append("### FAIBLE\n\n")
PARTS.append("17. WP Umbrella token absent du Credential Manager alors que la memoire l indique present. Peut signifier qu il est dans un autre store (1Password, fichier). A localiser pour confirmer la memoire.\n\n")
PARTS.append("18. PM2 absent localement\n")
PARTS.append("    Les apps PM2 ne tournent que sur xCloud. Coherent. Note pour le runbook incident : si PC compromis, les apps tournent toujours cote xCloud.\n\n")
PARTS.append("19. Taches planifiees : zero tache dev custom\n")
PARTS.append("    Pas de cron-style local. Tout passe par n8n ou apps xCloud. Coherent.\n\n")

PARTS.append("---\n\n## Recommandations pour les etapes suivantes du briefing\n\n")
PARTS.append("| Finding | Etape briefing | Priorite |\n|---|---|---|\n")
PARTS.append("| #1, #2, #5, #10 | Etape 7 (rotation) + Etape 8 (vault) | P0, semaine 1-2 |\n")
PARTS.append("| #3, #11 | Etape 4 (secrets inventory + rotation immediate) | P0, AVANT etape 5 |\n")
PARTS.append("| #4, #14, #15 | Hardening PC dev (a ajouter en phase 0bis ?) | P1, semaine 2 |\n")
PARTS.append("| #6 | Manuel, immediat | P0, ce soir |\n")
PARTS.append("| #7, #8 | Etape 7 (rotation + scoping) | P1 |\n")
PARTS.append("| #9 | Manuel via Kaspersky UI | P1 |\n")
PARTS.append("| #12, #13, #16 | Cleanup workspace (hors briefing) | P2, mois 1 |\n")
PARTS.append("| #17, #18, #19 | Note pour etape 14 (runbook incident) | P2 |\n\n")
PARTS.append("## Etape 1 terminee. En attente validation pour etape 2 (inventaire WP).\n")

output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "01-pc-inventory.md")
with open(output_path, "w", encoding="utf-8") as f:
    f.write("".join(PARTS))

print("WRITTEN:", output_path, "=", os.path.getsize(output_path), "bytes")
